export type DonationReceiptLocale = 'bn-BD' | 'en';

export type DonationCountry = {
  serial: number;
  code: string;
  name: string;
  receiptLocale: DonationReceiptLocale;
};

export const DONATION_COUNTRIES: DonationCountry[] = [
  { serial: 1, code: 'BD', name: 'Bangladesh', receiptLocale: 'bn-BD' },
  { serial: 2, code: 'AF', name: 'Afghanistan', receiptLocale: 'en' },
  { serial: 3, code: 'AX', name: 'Aland Islands', receiptLocale: 'en' },
  { serial: 4, code: 'AL', name: 'Albania', receiptLocale: 'en' },
  { serial: 5, code: 'DZ', name: 'Algeria', receiptLocale: 'en' },
  { serial: 6, code: 'AS', name: 'American Samoa', receiptLocale: 'en' },
  { serial: 7, code: 'AD', name: 'Andorra', receiptLocale: 'en' },
  { serial: 8, code: 'AO', name: 'Angola', receiptLocale: 'en' },
  { serial: 9, code: 'AI', name: 'Anguilla', receiptLocale: 'en' },
  { serial: 10, code: 'AQ', name: 'Antarctica', receiptLocale: 'en' },
  { serial: 11, code: 'AG', name: 'Antigua and Barbuda', receiptLocale: 'en' },
  { serial: 12, code: 'AR', name: 'Argentina', receiptLocale: 'en' },
  { serial: 13, code: 'AM', name: 'Armenia', receiptLocale: 'en' },
  { serial: 14, code: 'AW', name: 'Aruba', receiptLocale: 'en' },
  { serial: 15, code: 'AU', name: 'Australia', receiptLocale: 'en' },
  { serial: 16, code: 'AT', name: 'Austria', receiptLocale: 'en' },
  { serial: 17, code: 'AZ', name: 'Azerbaijan', receiptLocale: 'en' },
  { serial: 18, code: 'BS', name: 'Bahamas', receiptLocale: 'en' },
  { serial: 19, code: 'BH', name: 'Bahrain', receiptLocale: 'en' },
  { serial: 20, code: 'BB', name: 'Barbados', receiptLocale: 'en' },
  { serial: 21, code: 'BY', name: 'Belarus', receiptLocale: 'en' },
  { serial: 22, code: 'BE', name: 'Belgium', receiptLocale: 'en' },
  { serial: 23, code: 'BZ', name: 'Belize', receiptLocale: 'en' },
  { serial: 24, code: 'BJ', name: 'Benin', receiptLocale: 'en' },
  { serial: 25, code: 'BM', name: 'Bermuda', receiptLocale: 'en' },
  { serial: 26, code: 'BT', name: 'Bhutan', receiptLocale: 'en' },
  { serial: 27, code: 'BO', name: 'Bolivia', receiptLocale: 'en' },
  { serial: 28, code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', receiptLocale: 'en' },
  { serial: 29, code: 'BA', name: 'Bosnia and Herzegovina', receiptLocale: 'en' },
  { serial: 30, code: 'BW', name: 'Botswana', receiptLocale: 'en' },
  { serial: 31, code: 'BV', name: 'Bouvet Island', receiptLocale: 'en' },
  { serial: 32, code: 'BR', name: 'Brazil', receiptLocale: 'en' },
  { serial: 33, code: 'IO', name: 'British Indian Ocean Territory', receiptLocale: 'en' },
  { serial: 34, code: 'BN', name: 'Brunei Darussalam', receiptLocale: 'en' },
  { serial: 35, code: 'BG', name: 'Bulgaria', receiptLocale: 'en' },
  { serial: 36, code: 'BF', name: 'Burkina Faso', receiptLocale: 'en' },
  { serial: 37, code: 'BI', name: 'Burundi', receiptLocale: 'en' },
  { serial: 38, code: 'CV', name: 'Cabo Verde', receiptLocale: 'en' },
  { serial: 39, code: 'KH', name: 'Cambodia', receiptLocale: 'en' },
  { serial: 40, code: 'CM', name: 'Cameroon', receiptLocale: 'en' },
  { serial: 41, code: 'CA', name: 'Canada', receiptLocale: 'en' },
  { serial: 42, code: 'KY', name: 'Cayman Islands', receiptLocale: 'en' },
  { serial: 43, code: 'CF', name: 'Central African Republic', receiptLocale: 'en' },
  { serial: 44, code: 'TD', name: 'Chad', receiptLocale: 'en' },
  { serial: 45, code: 'CL', name: 'Chile', receiptLocale: 'en' },
  { serial: 46, code: 'CN', name: 'China', receiptLocale: 'en' },
  { serial: 47, code: 'CX', name: 'Christmas Island', receiptLocale: 'en' },
  { serial: 48, code: 'CC', name: 'Cocos (Keeling) Islands', receiptLocale: 'en' },
  { serial: 49, code: 'CO', name: 'Colombia', receiptLocale: 'en' },
  { serial: 50, code: 'KM', name: 'Comoros', receiptLocale: 'en' },
  { serial: 51, code: 'CG', name: 'Congo', receiptLocale: 'en' },
  { serial: 52, code: 'CD', name: 'Congo, Democratic Republic of the', receiptLocale: 'en' },
  { serial: 53, code: 'CK', name: 'Cook Islands', receiptLocale: 'en' },
  { serial: 54, code: 'CR', name: 'Costa Rica', receiptLocale: 'en' },
  { serial: 55, code: 'CI', name: "Cote d'Ivoire", receiptLocale: 'en' },
  { serial: 56, code: 'HR', name: 'Croatia', receiptLocale: 'en' },
  { serial: 57, code: 'CU', name: 'Cuba', receiptLocale: 'en' },
  { serial: 58, code: 'CW', name: 'Curacao', receiptLocale: 'en' },
  { serial: 59, code: 'CY', name: 'Cyprus', receiptLocale: 'en' },
  { serial: 60, code: 'CZ', name: 'Czechia', receiptLocale: 'en' },
  { serial: 61, code: 'DK', name: 'Denmark', receiptLocale: 'en' },
  { serial: 62, code: 'DJ', name: 'Djibouti', receiptLocale: 'en' },
  { serial: 63, code: 'DM', name: 'Dominica', receiptLocale: 'en' },
  { serial: 64, code: 'DO', name: 'Dominican Republic', receiptLocale: 'en' },
  { serial: 65, code: 'EC', name: 'Ecuador', receiptLocale: 'en' },
  { serial: 66, code: 'EG', name: 'Egypt', receiptLocale: 'en' },
  { serial: 67, code: 'SV', name: 'El Salvador', receiptLocale: 'en' },
  { serial: 68, code: 'GQ', name: 'Equatorial Guinea', receiptLocale: 'en' },
  { serial: 69, code: 'ER', name: 'Eritrea', receiptLocale: 'en' },
  { serial: 70, code: 'EE', name: 'Estonia', receiptLocale: 'en' },
  { serial: 71, code: 'SZ', name: 'Eswatini', receiptLocale: 'en' },
  { serial: 72, code: 'ET', name: 'Ethiopia', receiptLocale: 'en' },
  { serial: 73, code: 'FK', name: 'Falkland Islands (Malvinas)', receiptLocale: 'en' },
  { serial: 74, code: 'FO', name: 'Faroe Islands', receiptLocale: 'en' },
  { serial: 75, code: 'FJ', name: 'Fiji', receiptLocale: 'en' },
  { serial: 76, code: 'FI', name: 'Finland', receiptLocale: 'en' },
  { serial: 77, code: 'FR', name: 'France', receiptLocale: 'en' },
  { serial: 78, code: 'GF', name: 'French Guiana', receiptLocale: 'en' },
  { serial: 79, code: 'PF', name: 'French Polynesia', receiptLocale: 'en' },
  { serial: 80, code: 'TF', name: 'French Southern Territories', receiptLocale: 'en' },
  { serial: 81, code: 'GA', name: 'Gabon', receiptLocale: 'en' },
  { serial: 82, code: 'GM', name: 'Gambia', receiptLocale: 'en' },
  { serial: 83, code: 'GE', name: 'Georgia', receiptLocale: 'en' },
  { serial: 84, code: 'DE', name: 'Germany', receiptLocale: 'en' },
  { serial: 85, code: 'GH', name: 'Ghana', receiptLocale: 'en' },
  { serial: 86, code: 'GI', name: 'Gibraltar', receiptLocale: 'en' },
  { serial: 87, code: 'GR', name: 'Greece', receiptLocale: 'en' },
  { serial: 88, code: 'GL', name: 'Greenland', receiptLocale: 'en' },
  { serial: 89, code: 'GD', name: 'Grenada', receiptLocale: 'en' },
  { serial: 90, code: 'GP', name: 'Guadeloupe', receiptLocale: 'en' },
  { serial: 91, code: 'GU', name: 'Guam', receiptLocale: 'en' },
  { serial: 92, code: 'GT', name: 'Guatemala', receiptLocale: 'en' },
  { serial: 93, code: 'GG', name: 'Guernsey', receiptLocale: 'en' },
  { serial: 94, code: 'GN', name: 'Guinea', receiptLocale: 'en' },
  { serial: 95, code: 'GW', name: 'Guinea-Bissau', receiptLocale: 'en' },
  { serial: 96, code: 'GY', name: 'Guyana', receiptLocale: 'en' },
  { serial: 97, code: 'HT', name: 'Haiti', receiptLocale: 'en' },
  { serial: 98, code: 'HM', name: 'Heard Island and McDonald Islands', receiptLocale: 'en' },
  { serial: 99, code: 'VA', name: 'Holy See', receiptLocale: 'en' },
  { serial: 100, code: 'HN', name: 'Honduras', receiptLocale: 'en' },
  { serial: 101, code: 'HK', name: 'Hong Kong', receiptLocale: 'en' },
  { serial: 102, code: 'HU', name: 'Hungary', receiptLocale: 'en' },
  { serial: 103, code: 'IS', name: 'Iceland', receiptLocale: 'en' },
  { serial: 104, code: 'IN', name: 'India', receiptLocale: 'en' },
  { serial: 105, code: 'ID', name: 'Indonesia', receiptLocale: 'en' },
  { serial: 106, code: 'IR', name: 'Iran', receiptLocale: 'en' },
  { serial: 107, code: 'IQ', name: 'Iraq', receiptLocale: 'en' },
  { serial: 108, code: 'IE', name: 'Ireland', receiptLocale: 'en' },
  { serial: 109, code: 'IM', name: 'Isle of Man', receiptLocale: 'en' },
  { serial: 110, code: 'IL', name: 'Israel', receiptLocale: 'en' },
  { serial: 111, code: 'IT', name: 'Italy', receiptLocale: 'en' },
  { serial: 112, code: 'JM', name: 'Jamaica', receiptLocale: 'en' },
  { serial: 113, code: 'JP', name: 'Japan', receiptLocale: 'en' },
  { serial: 114, code: 'JE', name: 'Jersey', receiptLocale: 'en' },
  { serial: 115, code: 'JO', name: 'Jordan', receiptLocale: 'en' },
  { serial: 116, code: 'KZ', name: 'Kazakhstan', receiptLocale: 'en' },
  { serial: 117, code: 'KE', name: 'Kenya', receiptLocale: 'en' },
  { serial: 118, code: 'KI', name: 'Kiribati', receiptLocale: 'en' },
  { serial: 119, code: 'KP', name: "Korea, Democratic People's Republic of", receiptLocale: 'en' },
  { serial: 120, code: 'KR', name: 'Korea, Republic of', receiptLocale: 'en' },
  { serial: 121, code: 'KW', name: 'Kuwait', receiptLocale: 'en' },
  { serial: 122, code: 'KG', name: 'Kyrgyzstan', receiptLocale: 'en' },
  { serial: 123, code: 'LA', name: "Lao People's Democratic Republic", receiptLocale: 'en' },
  { serial: 124, code: 'LV', name: 'Latvia', receiptLocale: 'en' },
  { serial: 125, code: 'LB', name: 'Lebanon', receiptLocale: 'en' },
  { serial: 126, code: 'LS', name: 'Lesotho', receiptLocale: 'en' },
  { serial: 127, code: 'LR', name: 'Liberia', receiptLocale: 'en' },
  { serial: 128, code: 'LY', name: 'Libya', receiptLocale: 'en' },
  { serial: 129, code: 'LI', name: 'Liechtenstein', receiptLocale: 'en' },
  { serial: 130, code: 'LT', name: 'Lithuania', receiptLocale: 'en' },
  { serial: 131, code: 'LU', name: 'Luxembourg', receiptLocale: 'en' },
  { serial: 132, code: 'MO', name: 'Macao', receiptLocale: 'en' },
  { serial: 133, code: 'MG', name: 'Madagascar', receiptLocale: 'en' },
  { serial: 134, code: 'MW', name: 'Malawi', receiptLocale: 'en' },
  { serial: 135, code: 'MY', name: 'Malaysia', receiptLocale: 'en' },
  { serial: 136, code: 'MV', name: 'Maldives', receiptLocale: 'en' },
  { serial: 137, code: 'ML', name: 'Mali', receiptLocale: 'en' },
  { serial: 138, code: 'MT', name: 'Malta', receiptLocale: 'en' },
  { serial: 139, code: 'MH', name: 'Marshall Islands', receiptLocale: 'en' },
  { serial: 140, code: 'MQ', name: 'Martinique', receiptLocale: 'en' },
  { serial: 141, code: 'MR', name: 'Mauritania', receiptLocale: 'en' },
  { serial: 142, code: 'MU', name: 'Mauritius', receiptLocale: 'en' },
  { serial: 143, code: 'YT', name: 'Mayotte', receiptLocale: 'en' },
  { serial: 144, code: 'MX', name: 'Mexico', receiptLocale: 'en' },
  { serial: 145, code: 'FM', name: 'Micronesia', receiptLocale: 'en' },
  { serial: 146, code: 'MD', name: 'Moldova', receiptLocale: 'en' },
  { serial: 147, code: 'MC', name: 'Monaco', receiptLocale: 'en' },
  { serial: 148, code: 'MN', name: 'Mongolia', receiptLocale: 'en' },
  { serial: 149, code: 'ME', name: 'Montenegro', receiptLocale: 'en' },
  { serial: 150, code: 'MS', name: 'Montserrat', receiptLocale: 'en' },
  { serial: 151, code: 'MA', name: 'Morocco', receiptLocale: 'en' },
  { serial: 152, code: 'MZ', name: 'Mozambique', receiptLocale: 'en' },
  { serial: 153, code: 'MM', name: 'Myanmar', receiptLocale: 'en' },
  { serial: 154, code: 'NA', name: 'Namibia', receiptLocale: 'en' },
  { serial: 155, code: 'NR', name: 'Nauru', receiptLocale: 'en' },
  { serial: 156, code: 'NP', name: 'Nepal', receiptLocale: 'en' },
  { serial: 157, code: 'NL', name: 'Netherlands', receiptLocale: 'en' },
  { serial: 158, code: 'NC', name: 'New Caledonia', receiptLocale: 'en' },
  { serial: 159, code: 'NZ', name: 'New Zealand', receiptLocale: 'en' },
  { serial: 160, code: 'NI', name: 'Nicaragua', receiptLocale: 'en' },
  { serial: 161, code: 'NE', name: 'Niger', receiptLocale: 'en' },
  { serial: 162, code: 'NG', name: 'Nigeria', receiptLocale: 'en' },
  { serial: 163, code: 'NU', name: 'Niue', receiptLocale: 'en' },
  { serial: 164, code: 'NF', name: 'Norfolk Island', receiptLocale: 'en' },
  { serial: 165, code: 'MK', name: 'North Macedonia', receiptLocale: 'en' },
  { serial: 166, code: 'MP', name: 'Northern Mariana Islands', receiptLocale: 'en' },
  { serial: 167, code: 'NO', name: 'Norway', receiptLocale: 'en' },
  { serial: 168, code: 'OM', name: 'Oman', receiptLocale: 'en' },
  { serial: 169, code: 'PK', name: 'Pakistan', receiptLocale: 'en' },
  { serial: 170, code: 'PW', name: 'Palau', receiptLocale: 'en' },
  { serial: 171, code: 'PS', name: 'Palestine, State of', receiptLocale: 'en' },
  { serial: 172, code: 'PA', name: 'Panama', receiptLocale: 'en' },
  { serial: 173, code: 'PG', name: 'Papua New Guinea', receiptLocale: 'en' },
  { serial: 174, code: 'PY', name: 'Paraguay', receiptLocale: 'en' },
  { serial: 175, code: 'PE', name: 'Peru', receiptLocale: 'en' },
  { serial: 176, code: 'PH', name: 'Philippines', receiptLocale: 'en' },
  { serial: 177, code: 'PN', name: 'Pitcairn', receiptLocale: 'en' },
  { serial: 178, code: 'PL', name: 'Poland', receiptLocale: 'en' },
  { serial: 179, code: 'PT', name: 'Portugal', receiptLocale: 'en' },
  { serial: 180, code: 'PR', name: 'Puerto Rico', receiptLocale: 'en' },
  { serial: 181, code: 'QA', name: 'Qatar', receiptLocale: 'en' },
  { serial: 182, code: 'RE', name: 'Reunion', receiptLocale: 'en' },
  { serial: 183, code: 'RO', name: 'Romania', receiptLocale: 'en' },
  { serial: 184, code: 'RU', name: 'Russian Federation', receiptLocale: 'en' },
  { serial: 185, code: 'RW', name: 'Rwanda', receiptLocale: 'en' },
  { serial: 186, code: 'BL', name: 'Saint Barthelemy', receiptLocale: 'en' },
  { serial: 187, code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', receiptLocale: 'en' },
  { serial: 188, code: 'KN', name: 'Saint Kitts and Nevis', receiptLocale: 'en' },
  { serial: 189, code: 'LC', name: 'Saint Lucia', receiptLocale: 'en' },
  { serial: 190, code: 'MF', name: 'Saint Martin (French part)', receiptLocale: 'en' },
  { serial: 191, code: 'PM', name: 'Saint Pierre and Miquelon', receiptLocale: 'en' },
  { serial: 192, code: 'VC', name: 'Saint Vincent and the Grenadines', receiptLocale: 'en' },
  { serial: 193, code: 'WS', name: 'Samoa', receiptLocale: 'en' },
  { serial: 194, code: 'SM', name: 'San Marino', receiptLocale: 'en' },
  { serial: 195, code: 'ST', name: 'Sao Tome and Principe', receiptLocale: 'en' },
  { serial: 196, code: 'SA', name: 'Saudi Arabia', receiptLocale: 'en' },
  { serial: 197, code: 'SN', name: 'Senegal', receiptLocale: 'en' },
  { serial: 198, code: 'RS', name: 'Serbia', receiptLocale: 'en' },
  { serial: 199, code: 'SC', name: 'Seychelles', receiptLocale: 'en' },
  { serial: 200, code: 'SL', name: 'Sierra Leone', receiptLocale: 'en' },
  { serial: 201, code: 'SG', name: 'Singapore', receiptLocale: 'en' },
  { serial: 202, code: 'SX', name: 'Sint Maarten (Dutch part)', receiptLocale: 'en' },
  { serial: 203, code: 'SK', name: 'Slovakia', receiptLocale: 'en' },
  { serial: 204, code: 'SI', name: 'Slovenia', receiptLocale: 'en' },
  { serial: 205, code: 'SB', name: 'Solomon Islands', receiptLocale: 'en' },
  { serial: 206, code: 'SO', name: 'Somalia', receiptLocale: 'en' },
  { serial: 207, code: 'ZA', name: 'South Africa', receiptLocale: 'en' },
  { serial: 208, code: 'GS', name: 'South Georgia and the South Sandwich Islands', receiptLocale: 'en' },
  { serial: 209, code: 'SS', name: 'South Sudan', receiptLocale: 'en' },
  { serial: 210, code: 'ES', name: 'Spain', receiptLocale: 'en' },
  { serial: 211, code: 'LK', name: 'Sri Lanka', receiptLocale: 'en' },
  { serial: 212, code: 'SD', name: 'Sudan', receiptLocale: 'en' },
  { serial: 213, code: 'SR', name: 'Suriname', receiptLocale: 'en' },
  { serial: 214, code: 'SJ', name: 'Svalbard and Jan Mayen', receiptLocale: 'en' },
  { serial: 215, code: 'SE', name: 'Sweden', receiptLocale: 'en' },
  { serial: 216, code: 'CH', name: 'Switzerland', receiptLocale: 'en' },
  { serial: 217, code: 'SY', name: 'Syrian Arab Republic', receiptLocale: 'en' },
  { serial: 218, code: 'TW', name: 'Taiwan', receiptLocale: 'en' },
  { serial: 219, code: 'TJ', name: 'Tajikistan', receiptLocale: 'en' },
  { serial: 220, code: 'TZ', name: 'Tanzania', receiptLocale: 'en' },
  { serial: 221, code: 'TH', name: 'Thailand', receiptLocale: 'en' },
  { serial: 222, code: 'TL', name: 'Timor-Leste', receiptLocale: 'en' },
  { serial: 223, code: 'TG', name: 'Togo', receiptLocale: 'en' },
  { serial: 224, code: 'TK', name: 'Tokelau', receiptLocale: 'en' },
  { serial: 225, code: 'TO', name: 'Tonga', receiptLocale: 'en' },
  { serial: 226, code: 'TT', name: 'Trinidad and Tobago', receiptLocale: 'en' },
  { serial: 227, code: 'TN', name: 'Tunisia', receiptLocale: 'en' },
  { serial: 228, code: 'TR', name: 'Turkey', receiptLocale: 'en' },
  { serial: 229, code: 'TM', name: 'Turkmenistan', receiptLocale: 'en' },
  { serial: 230, code: 'TC', name: 'Turks and Caicos Islands', receiptLocale: 'en' },
  { serial: 231, code: 'TV', name: 'Tuvalu', receiptLocale: 'en' },
  { serial: 232, code: 'UG', name: 'Uganda', receiptLocale: 'en' },
  { serial: 233, code: 'UA', name: 'Ukraine', receiptLocale: 'en' },
  { serial: 234, code: 'AE', name: 'United Arab Emirates', receiptLocale: 'en' },
  { serial: 235, code: 'GB', name: 'United Kingdom', receiptLocale: 'en' },
  { serial: 236, code: 'US', name: 'United States', receiptLocale: 'en' },
  { serial: 237, code: 'UM', name: 'United States Minor Outlying Islands', receiptLocale: 'en' },
  { serial: 238, code: 'UY', name: 'Uruguay', receiptLocale: 'en' },
  { serial: 239, code: 'UZ', name: 'Uzbekistan', receiptLocale: 'en' },
  { serial: 240, code: 'VU', name: 'Vanuatu', receiptLocale: 'en' },
  { serial: 241, code: 'VE', name: 'Venezuela', receiptLocale: 'en' },
  { serial: 242, code: 'VN', name: 'Viet Nam', receiptLocale: 'en' },
  { serial: 243, code: 'VG', name: 'Virgin Islands, British', receiptLocale: 'en' },
  { serial: 244, code: 'VI', name: 'Virgin Islands, U.S.', receiptLocale: 'en' },
  { serial: 245, code: 'WF', name: 'Wallis and Futuna', receiptLocale: 'en' },
  { serial: 246, code: 'EH', name: 'Western Sahara', receiptLocale: 'en' },
  { serial: 247, code: 'YE', name: 'Yemen', receiptLocale: 'en' },
  { serial: 248, code: 'ZM', name: 'Zambia', receiptLocale: 'en' },
  { serial: 249, code: 'ZW', name: 'Zimbabwe', receiptLocale: 'en' },
  { serial: 250, code: 'OTHER', name: 'Other', receiptLocale: 'en' },
];

export function getDonationReceiptLocale(
  country: string | null | undefined,
): DonationReceiptLocale {
  if (!country) return 'bn-BD';
  const normalized = country.trim().toLowerCase();
  return normalized === 'bangladesh' ||
    normalized === 'bd' ||
    normalized === 'বাংলাদেশ'
    ? 'bn-BD'
    : 'en';
}

export function isBangladeshDonor(country: string | null | undefined): boolean {
  return getDonationReceiptLocale(country) === 'bn-BD';
}
