import type { DashboardData } from './types';

export const MOCK_DASHBOARD: DashboardData = {
  profileCompletion: 75,
  joinedAt: '2024-06-15T08:30:00Z',

  kpi: {
    membershipStatus: 'active',
    totalPets: 2,
    activeBookings: 1,
    totalContributions: 3000,
    certificates: 2,
    impactScore: 480,
  },

  membership: {
    tier: 'Care Partner',
    status: 'active',
    memberNumber: 'BPA-CP-2024-00142',
    validFrom: '2024-06-15',
    validUntil: '2025-06-14',
    zonePreference: 'Gulshan Zone',
    benefits: [
      'Free annual vaccination (up to 2 pets)',
      'Community clinic access',
      'Priority campaign registration',
      'Digital Care Partner Card',
      'Monthly transparency report',
    ],
  },

  pets: [
    {
      id: 'pet-001',
      name: 'Bruno',
      petType: 'dog',
      breed: 'Labrador Mix',
      gender: 'male',
      approxAge: 3,
      photoUrl: null,
    },
    {
      id: 'pet-002',
      name: 'Mimi',
      petType: 'cat',
      breed: 'Persian Mix',
      gender: 'female',
      approxAge: 2,
      photoUrl: null,
    },
  ],

  bookings: [
    {
      id: 'booking-001',
      bookingNumber: 'BPA-2024-VAC-00891',
      campaignTitle: 'Free Vaccination Drive – Dhaka South',
      campaignSlug: 'free-vaccination-drive-dhaka-south',
      sessionDate: '2024-12-10',
      petCount: 2,
      status: 'certificate_issued',
      paymentStatus: 'paid',
      hasCertificate: true,
      totalAmountBdt: 0,
    },
  ],

  contributions: [
    {
      id: 'contrib-001',
      contributionNumber: 'BPA-CONT-2024-00142',
      amountBdt: 3000,
      status: 'paid',
      zoneName: 'Gulshan Zone',
      planTitle: 'Care Partner Contribution',
      createdAt: '2024-06-15T09:00:00Z',
    },
  ],

  careCard: {
    cardId: 'BPA-CP-2024-00142',
    cardNumber: 'BPA-CP-2024-00142',
    status: 'active',
    zoneName: 'Gulshan Zone',
    zoneSlug: 'gulshan-zone',
    issuedAt: '2024-06-15',
    expiresAt: '2025-06-14',
    memberName: 'Demo User',
    verifyUrl: null,
  },

  impact: {
    vaccinatedPets: 4,
    supportedAnimals: 12,
    volunteerHours: 0,
    impactScore: 480,
    badges: [
      {
        id: 'badge-first-contributor',
        title: 'First Contributor',
        description: 'Made your first community contribution',
        icon: '🌱',
        earned: true,
        earnedAt: '2024-06-15',
      },
      {
        id: 'badge-vaccination-supporter',
        title: 'Vaccination Supporter',
        description: 'Supported a BPA vaccination campaign',
        icon: '💉',
        earned: true,
        earnedAt: '2024-12-10',
      },
      {
        id: 'badge-care-partner',
        title: 'Community Care Partner',
        description: 'Became a BPA Community Care Partner member',
        icon: '🤝',
        earned: true,
        earnedAt: '2024-06-15',
      },
      {
        id: 'badge-street-hero',
        title: 'Street Animal Hero',
        description: 'Contributed to street animal welfare programs',
        icon: '🐾',
        earned: false,
      },
      {
        id: 'badge-founding-member',
        title: 'Founding Member',
        description: 'Joined BPA in the founding year',
        icon: '⭐',
        earned: false,
      },
      {
        id: 'badge-zone-builder',
        title: 'Zone Builder',
        description: 'Helped establish a community zone',
        icon: '🏗️',
        earned: false,
      },
    ],
  },

  documents: [
    {
      id: 'doc-001',
      title: 'Care Partner Membership Card',
      type: 'membership_card',
      issuedAt: '2024-06-15',
      downloadUrl: null,
      verifyUrl: null,
    },
    {
      id: 'doc-002',
      title: 'Vaccination Certificate – Bruno',
      type: 'vaccination_certificate',
      issuedAt: '2024-12-10',
      downloadUrl: null,
      verifyUrl: null,
    },
    {
      id: 'doc-003',
      title: 'Payment Receipt – BPA-CONT-2024-00142',
      type: 'payment_receipt',
      issuedAt: '2024-06-15',
      downloadUrl: null,
      verifyUrl: null,
    },
    {
      id: 'doc-004',
      title: 'Validation Slip – BPA-2024-VAC-00891',
      type: 'validation_slip',
      issuedAt: '2024-12-10',
      downloadUrl: null,
      verifyUrl: null,
    },
    {
      id: 'doc-005',
      title: 'Care Partner Card',
      type: 'care_partner_card',
      issuedAt: '2024-06-15',
      downloadUrl: null,
      verifyUrl: null,
    },
  ],

  notifications: [
    {
      id: 'notif-001',
      type: 'membership_renewal',
      title: 'Membership Renewal Due Soon',
      message: 'Your Care Partner membership expires on June 14, 2025. Renew to keep enjoying benefits.',
      priority: 'high',
      actionUrl: '/community-pet-care/contribute',
    },
    {
      id: 'notif-002',
      type: 'certificate_ready',
      title: 'Certificate Ready for Download',
      message: 'Vaccination certificate for Bruno is ready to download.',
      priority: 'medium',
    },
    {
      id: 'notif-003',
      type: 'campaign_update',
      title: 'New Vaccination Drive Announced',
      message: 'Free vaccination drive in Gulshan Zone – December 2025. Register early!',
      priority: 'low',
      actionUrl: '/campaigns',
    },
  ],

  transparency: {
    totalFundBdt: 30000000,
    collectedBdt: 4250000,
    activeZones: 3,
    totalZones: 12,
    lastUpdated: '2025-06-01',
  },

  activity: [
    {
      id: 'act-001',
      type: 'certificate_issued',
      title: 'Vaccination Certificate Issued',
      description: 'Certificate issued for Bruno – Free Vaccination Drive',
      createdAt: '2024-12-11T09:15:00Z',
      referenceNumber: 'BPA-2024-VAC-00891',
    },
    {
      id: 'act-002',
      type: 'pet_vaccinated',
      title: 'Pet Vaccinated',
      description: 'Bruno & Mimi received vaccinations at the Dhaka South campaign',
      createdAt: '2024-12-10T11:30:00Z',
    },
    {
      id: 'act-003',
      type: 'payment_verified',
      title: 'Payment Verified',
      description: 'Care Partner contribution of ৳3,000 confirmed',
      createdAt: '2024-06-16T10:00:00Z',
      referenceNumber: 'BPA-CONT-2024-00142',
    },
    {
      id: 'act-004',
      type: 'membership_purchased',
      title: 'Membership Purchased',
      description: 'Care Partner membership activated for Gulshan Zone',
      createdAt: '2024-06-15T09:10:00Z',
    },
    {
      id: 'act-005',
      type: 'payment_submitted',
      title: 'Payment Submitted',
      description: 'Care Partner contribution of ৳3,000 submitted',
      createdAt: '2024-06-15T09:00:00Z',
      referenceNumber: 'BPA-CONT-2024-00142',
    },
    {
      id: 'act-006',
      type: 'campaign_registered',
      title: 'Campaign Registration',
      description: 'Registered for Free Vaccination Drive – Dhaka South',
      createdAt: '2024-11-25T14:00:00Z',
      referenceNumber: 'BPA-2024-VAC-00891',
    },
  ],
};
